###################################################
# header_factions.py
# This file contains declarations for factions
# DO NOT EDIT THIS FILE!
###################################################

ff_always_hide_label = 0x00000001
ff_max_rating_bits = 8
ff_max_rating_mask = 0x0000ff00

def max_player_rating(rating):
  r = 100 - rating
  return (r << ff_max_rating_bits) & ff_max_rating_mask
